[[permission]]
identifier = "allow-get-my-name"
description = "Allows reading the current username"
commands.allow = ["get_my_name"]

[[permission]]
identifier = "allow-get-my-id"
description = "Allows reading the current user ID"
commands.allow = ["get_my_id"]

[[permission]]
identifier = "allow-update-my-name"
description = "Allows updating the username"
commands.allow = ["update_my_name"]

[[permission]]
identifier = "allow-get-peers"
description = "Allows getting the list of online peers"
commands.allow = ["get_peers"]

[[permission]]
identifier = "allow-send-message"
description = "Allows sending text messages"
commands.allow = ["send_message"]

[[permission]]
identifier = "allow-get-chat-history"
description = "Allows getting chat history"
commands.allow = ["get_chat_history"]

[[permission]]
identifier = "allow-send-file"
description = "Allows sending files to peers"
commands.allow = ["send_file"]

[[permission]]
identifier = "allow-get-settings"
description = "Allows reading application settings"
commands.allow = ["get_settings"]

[[permission]]
identifier = "allow-update-settings"
description = "Allows updating application settings"
commands.allow = ["update_settings"]

[[permission]]
identifier = "allow-get-theme-list"
description = "Allows getting the list of available themes"
commands.allow = ["get_theme_list"]

[[permission]]
identifier = "allow-get-theme-css"
description = "Allows reading theme CSS content"
commands.allow = ["get_theme_css"]

[[permission]]
identifier = "allow-save-current-theme"
description = "Allows saving the current theme preference"
commands.allow = ["save_current_theme"]

[[permission]]
identifier = "allow-get-current-theme"
description = "Allows reading the current theme preference"
commands.allow = ["get_current_theme"]


[[permission]]
identifier = "allow-accept-file"
description = "Allows accepting received files"
commands.allow = ["accept_file"]

[[permission]]
identifier = "allow-get-default-download-path"
description = "Allows getting the default download path"
commands.allow = ["get_default_download_path"]

[[permission]]
identifier = "allow-request-storage-permission"
description = "Allows requesting storage permission on Android"
commands.allow = ["request_storage_permission"]

[[permission]]
identifier = "allow-save-file-message"
description = "Allows saving file message to database"
commands.allow = ["save_file_message"]
